spring:
   datasource:
      username: continuing_seed
      password: continuing_seed
      url: jdbc:mysql://localhost:3306/continuing_seed
      
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      
   sql:
      init:
         mode: always

   logging:
      level:
         org:
            hibernate:
               SQL: DEBUG         